authors:
  <jossie>:
    name: Jossie Jiang    # Author name
    description: Learning By Sleeping # Author description
    avatar: https://avatars.githubusercontent.com/u/88167742?v=4  # Author avatar